#define USART_MAINBOARD_SERIAL                     &USARTD0
#define USART_MAINBOARD_SERIAL_RX_Vect             USARTD0_RXC_vect
#define USART_MAINBOARD_SERIAL_BAUDRATE            115200
#define USART_MAINBOARD_SERIAL_CHAR_LENGTH         USART_CHSIZE_8BIT_gc
#define USART_MAINBOARD_SERIAL_PARITY              USART_PMODE_DISABLED_gc
#define USART_MAINBOARD_SERIAL_STOP_BIT            false
